/* ============================================================================
   ALL CONTENT LIVES HERE. Edit freely — app.js only renders what it finds.
   Prices in DKK (≈ 7.45 DKK = 1 €). Hours change: verify before relying on them.
   ============================================================================ */
const DATA = {

  // ---------------------------------------------------------------- TRIP ----
  trip: {
    edition: "Family edition",
    city: "København",
    dates: "26–28 Sep 2026",
    tag: "26–28 SEP 2026",
    who: "the family",
    intro: "Three days on foot. <b>Six lines</b> to choose from, one <b>PhD defence</b> to celebrate.",
    tourIntro: "Each line is a self-contained half-day walk with coffee, lunch and sit-downs built in. Pick by mood; they all pass the big sights.",
    toursPage: "Every line is walkable at a relaxed pace (5–6 km, lots of stops). Distances are honest, times are generous. Mix and match: Line 3 in the morning and Line 2 after lunch is a classic full day.",
    days: [
      { label: "Sat 26", title: "Arrive · The Postcard", sub: "Nyhavn → Little Mermaid, then a bodega", color: "l1", href: "#/tour/l1" },
      { label: "Sun 27", title: "Old Town → Harbour", sub: "Line 3 morning, Line 2 afternoon", color: "l3", href: "#/tour/l3" },
      { label: "Mon 28", title: "Defence day ★", sub: "13:00 DTU · celebrate · fly 19:00", color: "lx", href: "#/defence", star: true },
    ],
    bigDay: {
      label: "Mon 28 Sep · 13:00 · DTU Lyngby",
      title: "PhD defence day",
      sub: "how to get there, where to celebrate afterwards, and how to make the 19:00 flight.",
    },
    footer: "Built for the September 2026 visit · reusable for the next one (see README) · Prices are rough, opening hours change — tap “Google Maps” on any place to check live hours before you walk.",
  },

  // -------------------------------------------------------------- PLACES ----
  // kind: sight | food | bar | transit.  addr is used for Google Maps lookups.
  places: {
    // Line 1 · The Postcard
    "kongens-nytorv": { name: "Kongens Nytorv", lat: 55.68006, lng: 12.58656, kind: "sight", blurb: "The King's New Square: Royal Theatre, Hotel d'Angleterre, Magasin du Nord. Metro hub for every line.", time: "10 min", cost: "Free" },
    "nyhavn": { name: "Nyhavn", lat: 55.67974, lng: 12.59089, kind: "sight", blurb: "The postcard: 17th-century colour-block houses along the old harbour. Hans Christian Andersen lived at No. 20, 67 and 18.", tip: "Walk the sunny (north) side. Don't eat here — prices are double. A takeaway beer on the pier edge is what locals do.", time: "30 min", cost: "Free" },
    "inderhavnsbroen": { name: "Inderhavnsbroen (the Kissing Bridge)", lat: 55.67855, lng: 12.59424, kind: "sight", blurb: "Pedestrian/bike bridge at the end of Nyhavn. Walk to the middle for the best view of the Opera and Christianshavn.", time: "10 min", cost: "Free" },
    "amalienborg": { name: "Amalienborg Palace", lat: 55.68396, lng: 12.59308, kind: "sight", blurb: "Four identical rococo palaces around an octagonal square — the King's winter home. Changing of the Royal Guard every day at 12:00.", tip: "Guards march from Rosenborg at 11:30 and arrive here at 12:00. Stand on the Marble Church side for the view. The museum inside is optional (≈125 kr).", time: "25 min", cost: "Free (square)", hours: "Guard change 12:00 daily" },
    "marble-church": { name: "Frederik's Church (Marble Church)", lat: 55.68497, lng: 12.58955, kind: "sight", blurb: "Scandinavia's biggest church dome. Free to walk in; the dome climb runs once a day at 13:00 (weekends in autumn).", time: "20 min", cost: "Free · dome ≈35 kr", hours: "10–17ish, dome 13:00" },
    "designmuseum": { name: "Designmuseum Danmark", lat: 55.68637, lng: 12.59441, kind: "sight", blurb: "Danish chairs, lamps and the story of why everything here looks good. Nice café courtyard.", time: "60 min", cost: "≈140 kr", hours: "Tue–Sun 10–18, closed Mon" },
    "nyboder": { name: "Nyboder", lat: 55.68920, lng: 12.58676, kind: "sight", blurb: "Rows of ochre-yellow 17th-century navy houses. Two minutes of very photogenic streets.", time: "10 min", cost: "Free" },
    "kastellet": { name: "Kastellet", lat: 55.69138, lng: 12.59374, kind: "sight", blurb: "A star-shaped fortress from 1660 that's still a working barracks. Walk the grassy ramparts past the windmill.", tip: "Go up on the ramparts (the earth walls) — that's where the views and the calm are.", time: "30 min", cost: "Free", hours: "06–22" },
    "gefion": { name: "Gefion Fountain & St Alban's", lat: 55.68928, lng: 12.59759, kind: "sight", blurb: "The goddess Gefion ploughing Zealand out of Sweden with four oxen; next to it the English church, a slice of Kent in Copenhagen.", time: "10 min", cost: "Free" },
    "little-mermaid": { name: "The Little Mermaid", lat: 55.69287, lng: 12.59929, kind: "sight", blurb: "Small (1.25 m), crowded, and mandatory. Five minutes of photos and you've done it.", tip: "Best light and fewest people before 10:00 or after 17:00. Cruise-ship crowds peak 11–15.", time: "15 min", cost: "Free" },
    "osterport": { name: "Østerport Station", lat: 55.69314, lng: 12.58877, kind: "transit", blurb: "S-train and regional trains. Two stops to Nørreport, or walk back through Kastellet/Bredgade in 30 min.", cost: "24 kr (2 zones)" },
    "told-snaps": { name: "Told & Snaps", lat: 55.67999, lng: 12.59175, kind: "food", addr: "Toldbodgade 2", blurb: "Classic smørrebrød right at the end of Nyhavn, 20 house-made snaps. The sensible lunch on Line 1.", hours: "Daily 11:30–16:00" },

    // Line 2 · Harbour & Christianshavn
    "gammel-strand": { name: "Gammel Strand", lat: 55.67765, lng: 12.57863, kind: "sight", blurb: "The old fish market quay facing Christiansborg across the canal. Metro M3/M4 exits right here.", time: "10 min", cost: "Free" },
    "christiansborg": { name: "Christiansborg Palace & Tower", lat: 55.67565, lng: 12.58004, kind: "sight", blurb: "Parliament, Supreme Court and the royal reception rooms in one building. The tower is the highest in the city and it's free.", tip: "The Tower: free, airport-style security, queues at weekends. Tue–Sat 11–21, Sun 11–17:30, closed Mon. The reception rooms and the medieval ruins underneath are the paid bits.", time: "45 min", cost: "Tower free · rooms ≈175 kr", hours: "Tower closed Mon" },
    "thorvaldsens": { name: "Thorvaldsens Museum", lat: 55.67675, lng: 12.57879, kind: "sight", blurb: "Denmark's sculptor-superstar in a wildly coloured 1848 building. Free on Wednesdays.", time: "45 min", cost: "≈110 kr · Wed free", hours: "Tue–Sun 10–17" },
    "black-diamond": { name: "The Black Diamond (Royal Library)", lat: 55.67355, lng: 12.58286, kind: "sight", blurb: "Polished black granite extension of the Royal Library leaning over the harbour. Free to walk in; the atrium and waterfront steps are the point.", time: "15 min", cost: "Free", hours: "Mon–Sat 08–21" },
    "borsen": { name: "Børsen", lat: 55.67639, lng: 12.58265, kind: "sight", blurb: "The 1625 stock exchange with the spire of four twisted dragon tails. Badly burned in April 2024 — being rebuilt, so this is a look-from-outside stop.", time: "5 min", cost: "Free" },
    "knippelsbro": { name: "Knippelsbro", lat: 55.67464, lng: 12.58743, kind: "sight", blurb: "Copper-green bascule bridge from 1937 into Christianshavn. The little tower on it is occasionally a pop-up café.", time: "5 min", cost: "Free" },
    "christianshavn-torv": { name: "Christianshavn canals", lat: 55.67207, lng: 12.59136, kind: "sight", blurb: "Copenhagen's 'little Amsterdam': houseboats, 17th-century warehouses, Overgaden Oven Vandet. The original Lagkagehuset bakery is on Torvegade.", tip: "Wander Wildersgade and Sankt Annæ Gade — both prettier than the main street.", time: "25 min", cost: "Free" },
    "our-saviour": { name: "Church of Our Saviour", lat: 55.67291, lng: 12.59425, kind: "sight", blurb: "The corkscrew spire: 400 steps, the last 150 outside, spiralling narrower until the stairs stop. Best view/thrill ratio in town.", tip: "Book a time slot online (kirkens site) — walk-ups queue. Closes in wind or rain. Not for anyone with vertigo; the church itself is free.", time: "45 min", cost: "≈75 kr", hours: "Daily 09–20" },
    "christiania-main": { name: "Freetown Christiania", lat: 55.67343, lng: 12.59999, kind: "sight", blurb: "Self-governing commune since 1971 on an old military base: hand-built houses, murals, cafés, a lake. Pusher Street's hash stalls were closed and the street dug up in 2024.", tip: "Enter from Prinsessegade. No photos in the central Green Light District. Walk the lake path along the ramparts — the houses there are the real attraction. Cash still helps in places.", time: "60 min", cost: "Free" },
    "morgenstedet": { name: "Morgenstedet", lat: 55.67375, lng: 12.60319, kind: "food", addr: "Langgaden, Christiania", blurb: "Vegetarian/vegan canteen in Christiania. One daily plate, big portions, garden seating.", hours: "Tue–Sun 12–21, closed Mon" },
    "broens-gadekokken": { name: "Broens Gadekøkken", lat: 55.67786, lng: 12.59682, kind: "food", addr: "Strandgade 95", blurb: "Street-food stalls on the quay at the Christianshavn end of the Kissing Bridge. Cheaper and closer than Reffen.", hours: "Season Mar–Oct, ≈11–21" },

    // Line 3 · Old Town
    "radhuspladsen": { name: "Rådhuspladsen (City Hall Square)", lat: 55.67606, lng: 12.56891, kind: "sight", blurb: "City Hall (1905) with the dragon fountain and the Hans Christian Andersen statue looking at Tivoli. The hall itself is free to wander on weekdays.", time: "15 min", cost: "Free", hours: "City Hall Mon–Fri 09–16" },
    "gammeltorv": { name: "Strøget · Gammeltorv & Nytorv", lat: 55.67814, lng: 12.57208, kind: "sight", blurb: "Start of Europe's longest pedestrian street. Gammeltorv has the 1608 Caritas fountain; Nytorv the old courthouse.", tip: "The parallel 'Strædet' (Kompagnistræde/Læderstræde) is the same idea with better shops and no chains.", time: "20 min", cost: "Free" },
    "vor-frue-kirke": { name: "Copenhagen Cathedral & Latin Quarter", lat: 55.67938, lng: 12.57273, kind: "sight", blurb: "Neoclassical cathedral with Thorvaldsen's Christ and apostles inside. Around it: the old university quarter, bookshops, Fiolstræde.", time: "20 min", cost: "Free" },
    "graabrodretorv": { name: "Gråbrødretorv", lat: 55.67986, lng: 12.57585, kind: "sight", blurb: "The cosiest square in the centre — pastel houses, plane trees, tables outside. Sporvejen (burgers in a tram) is here.", time: "10 min", cost: "Free" },
    "round-tower": { name: "The Round Tower (Rundetaarn)", lat: 55.68136, lng: 12.57579, kind: "sight", blurb: "1642 observatory with a 209 m spiral ramp instead of stairs — a Tsar once rode up on horseback. Rooftop view over the old town.", tip: "Cheapest paid view in the city. The observatory dome is under restoration until October 2026, but the ramp and roof are open.", time: "30 min", cost: "60 kr · students 40", hours: "Daily 10–20 (Sept)" },
    "stroget-amagertorv": { name: "Amagertorv & the Stork Fountain", lat: 55.67879, lng: 12.57900, kind: "sight", blurb: "The heart of Strøget: Royal Copenhagen, Georg Jensen, Illum. The Illum rooftop terrace is a free view with cafés.", time: "20 min", cost: "Free" },
    "rosenborg": { name: "Rosenborg Castle & King's Garden", lat: 55.68569, lng: 12.57742, kind: "sight", blurb: "Christian IV's 1606 pleasure palace: the Crown Jewels in the basement, the Knights' Hall upstairs, the oldest royal garden outside.", tip: "Timed tickets online only (they sell out on weekends). If you skip the castle, the garden and the guard barracks are free — and you can watch the guards leave for Amalienborg at 11:30.", time: "60 min", cost: "140 kr · garden free", hours: "Daily 10–17 (Sept)" },
    "torvehallerne": { name: "Torvehallerne", lat: 55.68387, lng: 12.56955, kind: "food", addr: "Frederiksborggade 21", blurb: "Two glass food halls: smørrebrød (Hallernes), porridge (Grød), tacos (Hija de Sanchez), coffee (Coffee Collective), fish, cheese, pastries.", hours: "Mon–Thu 10–19, Fri 10–20, Sat 10–18, Sun 11–17" },
    "botanical-garden": { name: "Botanical Garden & Palm House", lat: 55.68691, lng: 12.57398, kind: "sight", blurb: "27 acres of free garden with an 1874 cast-iron Palm House you can climb inside. Lakes, ducks, a bench for every mood.", time: "30 min", cost: "Free", hours: "Garden 08:30–18, Palm House 10–15:30" },
    "orstedsparken": { name: "Ørstedsparken", lat: 55.68092, lng: 12.56633, kind: "sight", blurb: "Romantic park on the old ramparts with a lake and a small bar. A shortcut back to the centre.", time: "15 min", cost: "Free" },
    "norreport": { name: "Nørreport Station", lat: 55.68336, lng: 12.57163, kind: "transit", blurb: "Busiest station in Denmark: metro M1/M2, S-trains, regional trains, and the 15E/150S buses to DTU.", cost: "" },

    // Line 4 · Nørrebro
    "dronning-louises-bro": { name: "Dronning Louises Bro", lat: 55.68713, lng: 12.56266, kind: "sight", blurb: "The bridge over the Lakes where the whole city sits with a beer on a sunny afternoon. Bike-lane theatre included.", time: "15 min", cost: "Free" },
    "assistens": { name: "Assistens Kirkegård", lat: 55.68963, lng: 12.55231, kind: "sight", blurb: "Cemetery-park: Hans Christian Andersen, Søren Kierkegaard and Niels Bohr are here, and locals picnic between them. Enter from Kapelvej.", tip: "Andersen's grave is section P, near the Nørrebrogade wall; there are maps at the gates.", time: "40 min", cost: "Free", hours: "07–22" },
    "jaegersborggade": { name: "Jægersborggade", lat: 55.69251, lng: 12.54443, kind: "sight", blurb: "The street that made Nørrebro cool: ceramics studios, wine bars, Meyers bakery, Coffee Collective, Grød, Manfreds.", time: "30 min", cost: "Free" },
    "grod-jaegersborggade": { name: "GRØD", lat: 55.69362, lng: 12.54288, kind: "food", addr: "Jægersborggade 50", blurb: "The porridge bar that started a chain. Oat porridge with caramel and apple, or savoury bowls.", hours: "Daily ≈07:30–21" },
    "superkilen": { name: "Superkilen", lat: 55.69968, lng: 12.54240, kind: "sight", blurb: "Bjarke Ingels' park with objects from 60 nations: a Moroccan fountain, a Thai boxing ring, the red square, the black hill with white lines.", time: "20 min", cost: "Free" },
    "kebabistan": { name: "Kebabistan", lat: 55.69089, lng: 12.55433, kind: "food", addr: "Nørrebrogade 66", blurb: "The durum that people cross the city for. Counter service, queue moves fast.", hours: "Daily ≈11–late" },
    "elmegade": { name: "Elmegade & Sankt Hans Torv", lat: 55.68983, lng: 12.55847, kind: "sight", blurb: "Small bars, Ølbaren, Brus around the corner on Guldbergsgade. Where Line 4 turns into an evening.", time: "15 min", cost: "Free" },
    "blaagaards-plads": { name: "Blågårds Plads", lat: 55.68640, lng: 12.55706, kind: "sight", blurb: "Sunken square with sculptures and the cheapest strip of bars in the city on Blågårdsgade: Props, Harbo, Blågårds Apotek.", time: "15 min", cost: "Free" },

    // Line 5 · Vesterbro
    "central-station": { name: "Central Station (Hovedbanegård)", lat: 55.67276, lng: 12.56468, kind: "transit", blurb: "1911 wooden-hall station. Lockers downstairs if you need to dump bags.", cost: "" },
    "tivoli": { name: "Tivoli Gardens", lat: 55.67465, lng: 12.56566, kind: "sight", blurb: "1843 amusement park that inspired Disneyland. Note: closed between seasons 21 Sep–1 Oct 2026 — so for this visit it's the gates and the Nimb façade only.", tip: "If you come back in another season: go after dark, entry ≈155 kr, rides extra, Friday concerts free with entry.", time: "10 min", cost: "Closed 21 Sep–1 Oct" },
    "glyptotek": { name: "Ny Carlsberg Glyptotek", lat: 55.67253, lng: 12.57177, kind: "sight", blurb: "The brewer's art collection: Rodin, Degas, Gauguin, Roman heads — and a palm-filled Winter Garden with the best museum café in town.", time: "60 min", cost: "≈135 kr · Tue free", hours: "Tue–Sun 10–17, closed Mon" },
    "kodbyen": { name: "Kødbyen (Meatpacking District)", lat: 55.66777, lng: 12.55839, kind: "sight", blurb: "White-tiled 1930s meat market halls, now restaurants, galleries and bars. Dead by day in places, packed by night.", time: "30 min", cost: "Free" },
    "hija-de-sanchez": { name: "Hija de Sanchez", lat: 55.66890, lng: 12.55850, kind: "food", addr: "Slagterboderne 8", blurb: "Tacos by an ex-Noma pastry chef. Three tacos and a horchata is lunch.", hours: "Tue–Sun ≈12–21" },
    "istedgade": { name: "Istedgade", lat: 55.67018, lng: 12.55627, kind: "sight", blurb: "From red-light to brunch in 1.5 km. Coffee bars, vintage, the odd sex shop; the real Vesterbro.", time: "20 min", cost: "Free" },
    "vaernedamsvej": { name: "Værnedamsvej", lat: 55.67369, lng: 12.55007, kind: "sight", blurb: "'Little Paris': one short street of cheese shops, flower stalls, wine bars and Granola café. Coffee stop.", time: "20 min", cost: "Free" },
    "enghave-plads": { name: "Enghave Plads", lat: 55.66723, lng: 12.54679, kind: "transit", blurb: "Metro M3. Bail-out point if legs are done; otherwise on to Carlsberg.", cost: "" },
    "carlsberg-elephant-gate": { name: "Carlsberg Elephant Gate", lat: 55.66732, lng: 12.53220, kind: "sight", blurb: "Four granite elephants (1901) holding up a tower, the old brewery quarter behind them now a new neighbourhood. Free to walk through.", time: "20 min", cost: "Free" },
    "home-of-carlsberg": { name: "Home of Carlsberg", lat: 55.66459, lng: 12.53026, kind: "sight", blurb: "The visitor centre: brewing history, the world's biggest beer-bottle collection, a beer included in the ticket. Pricey; the gate and streets outside are the free version.", time: "90 min", cost: "215 kr incl. a beer", hours: "Daily 10–17ish (Sept)" },
    "cisternerne": { name: "Cisternerne", lat: 55.67180, lng: 12.52580, kind: "sight", blurb: "Underground 19th-century water reservoir in Søndermarken, now an art space with one dripping, echoing installation a year.", time: "40 min", cost: "≈130 kr", hours: "Tue–Sun, closed Mon" },
    "frederiksberg-have": { name: "Frederiksberg Have", lat: 55.67466, lng: 12.53128, kind: "sight", blurb: "Romantic 18th-century garden with canals, a Chinese pavilion and the palace on the hill. From the west edge you can watch the Zoo's elephants for free.", tip: "Enter at Frederiksberg Runddel; head for the elephant viewpoint by the Zoo fence, then loop the lake.", time: "45 min", cost: "Free", hours: "06–sunset" },
    "zoo": { name: "Copenhagen Zoo", lat: 55.67170, lng: 12.52328, kind: "sight", blurb: "One of Europe's oldest zoos, with Norman Foster's elephant house and BIG's panda enclosure.", time: "2–3 h", cost: "≈230 kr", hours: "Daily 10–17ish" },
    "frederiksberg-alle-st": { name: "Frederiksberg Allé Station", lat: 55.67351, lng: 12.54061, kind: "transit", blurb: "Metro M3 ring line back to the centre in 6 minutes.", cost: "24 kr" },

    // Line 6 · By Water
    "holmens-kirke": { name: "Holmens Kirke · Netto-Bådene pier", lat: 55.67660, lng: 12.58360, kind: "transit", blurb: "The naval church by Christiansborg; the Netto-Bådene canal tours leave from the quay in front of it (also from Nyhavn).", cost: "Canal tour ≈100 kr", hours: "Boats every 30 min ≈10–17 in Sept" },
    "refshaleoen-stop": { name: "Refshaleøen harbour-bus stop", lat: 55.69272, lng: 12.61151, kind: "transit", blurb: "Yellow harbour buses 991/992 stop here. They're normal public transport — a 2-zone ticket (24 kr) is the cheapest boat trip in Copenhagen.", cost: "24 kr (2 zones)" },
    "reffen": { name: "Reffen street food", lat: 55.69317, lng: 12.60978, kind: "food", addr: "Refshalevej 167A", blurb: "35 shipping-container food stalls on the old shipyard, everyone eating on the quay. Season runs to the end of September — confirm on reffen.dk before going.", hours: "Season Mar–Sep ≈11:30–21:30 (check)" },
    "la-banchina": { name: "La Banchina", lat: 55.68929, lng: 12.61091, kind: "food", addr: "Refshalevej 141", blurb: "Sixteen-seat harbour café with a swimming pier and a sauna. Fish of the day, natural wine, feet in the water.", hours: "Daily ≈09–22 (check)" },
    "lille-bakery": { name: "Lille Bakery", lat: 55.69009, lng: 12.61309, kind: "food", addr: "Refshalevej 213A", blurb: "Bakery-café in a former shipyard hall. Sourdough, buns, lunch plates; long communal tables.", hours: "Wed–Sun ≈08–15" },
    "copenhagen-contemporary": { name: "Copenhagen Contemporary", lat: 55.69341, lng: 12.61360, kind: "sight", blurb: "7,000 m² of installation art in an old welding hall. Big, immersive, worth it if a show clicks.", time: "60 min", cost: "≈140 kr", hours: "Wed–Sun 11–18" },
    "mikkeller-baghaven": { name: "Mikkeller Baghaven", lat: 55.69349, lng: 12.60786, kind: "bar", addr: "Refshalevej 169B", blurb: "Mikkeller's barrel-ageing brewery and taproom on the water. Sour and wild ales; not cheap, very good." },
    "copenhill": { name: "CopenHill (Amager Bakke)", lat: 55.68487, lng: 12.62110, kind: "sight", blurb: "A waste-to-energy plant with a ski slope on the roof. Hike the trail to the top for free; views to Sweden and over the whole harbour.", tip: "Take the elevator up and walk down, or hike the zig-zag trail. The rooftop bar sells beer; skiing and climbing are the only paid bits.", time: "45 min", cost: "Free (roof)", hours: "Mon–Fri 11–19, Sat 10–19, Sun 10–17" },
    "nordre-toldbod": { name: "Nordre Toldbod harbour-bus stop", lat: 55.68962, lng: 12.59891, kind: "transit", blurb: "Harbour bus back from Refshaleøen lands here, 5 minutes from Kastellet and the Little Mermaid.", cost: "24 kr" },

    // Bonus / other sights
    "islands-brygge-havnebad": { name: "Islands Brygge Harbour Bath", lat: 55.66852, lng: 12.57751, kind: "sight", blurb: "Open-air harbour pools by the waterfront park. In late September only the brave swim; the lawn and the view are free for everyone.", time: "20 min", cost: "Free" },
    "kalvebod-bolge": { name: "Kalvebod Bølge", lat: 55.66894, lng: 12.57508, kind: "sight", blurb: "Wavy wooden boardwalk over the water opposite Islands Brygge. Sit on the edge; kayaks go under you.", time: "15 min", cost: "Free" },
    "cykelslangen": { name: "Cykelslangen (the Bicycle Snake)", lat: 55.66262, lng: 12.56351, kind: "sight", blurb: "Orange elevated bike ramp snaking over the harbour. Pedestrians aren't allowed on it — watch it from Bryggebroen next door.", time: "10 min", cost: "Free" },
    "blox": { name: "BLOX · Danish Architecture Center", lat: 55.67218, lng: 12.57848, kind: "sight", blurb: "Green-glass stack by OMA on the waterfront. The DAC exhibitions are paid; the terraces and the playground under the road are free.", time: "30 min", cost: "Free · DAC ≈130 kr" },
    "opera": { name: "Copenhagen Opera House", lat: 55.68199, lng: 12.60074, kind: "sight", blurb: "The Maersk-funded opera on Holmen, best seen from across the water at Amalienborg or from the harbour bus.", time: "10 min", cost: "Free (outside)" },
    "stroget-illum": { name: "Illum rooftop", lat: 55.67927, lng: 12.58069, kind: "sight", blurb: "Department-store roof terrace with cafés and a free view over the spires of the old town.", time: "15 min", cost: "Free" },

    // Restaurants (not already listed above)
    "schonnemann": { name: "Restaurant Schønnemann", lat: 55.68277, lng: 12.57608, kind: "food", addr: "Hauser Plads 16", blurb: "Since 1877, the smørrebrød institution: sanded floors, 140 snaps, chefs from Noma at the next table. Lunch only.", hours: "Mon–Sat 11:30–17:00, closed Sun" },
    "aamanns-1921": { name: "Aamanns 1921", lat: 55.68021, lng: 12.57594, kind: "food", addr: "Niels Hemmingsens Gade 19", blurb: "Smørrebrød reinvented by Adam Aamann in a 1921 bank building. Michelin-listed, still a lunch place at heart.", hours: "Lunch daily 11:30–17 (last order 16:00), dinner from 17:30" },
    "kronborg-restaurant": { name: "Restaurant Kronborg", lat: 55.67758, lng: 12.57442, kind: "food", addr: "Brolæggerstræde 12", blurb: "Cellar smørrebrød restaurant two streets off Strøget. Same idea as Schønnemann, fewer tourists, gentler prices.", hours: "Mon–Sat ≈11–17, closed Sun" },
    "cafe-sorgenfri": { name: "Café Sorgenfri", lat: 55.67774, lng: 12.57476, kind: "food", addr: "Brolæggerstræde 8", blurb: "The bodega-restaurant: stegt flæsk, frikadeller, herring, beer, wood panels, all day. The most Danish room in the city.", hours: "Daily ≈11–21, kitchen all day" },
    "slotskaelderen": { name: "Slotskælderen hos Gitte Kik", lat: 55.67803, lng: 12.58094, kind: "food", addr: "Fortunstræde 4", blurb: "Politicians' lunch cellar opposite Christiansborg: pick your smørrebrød from the counter.", hours: "Tue–Sat 11–15, closed Sun–Mon" },
    "kanal-cafeen": { name: "Kanal Cafeen", lat: 55.67440, lng: 12.57679, kind: "food", addr: "Frederiksholms Kanal 18", blurb: "1852 lunch room by the canal, model ships on the ceiling, smørrebrød and snaps.", hours: "Mon–Fri 11:30–17, Sat 11:30–15, closed Sun" },
    "restaurant-puk": { name: "Restaurant Puk", lat: 55.67615, lng: 12.57394, kind: "food", addr: "Vandkunsten 8", blurb: "Low-ceilinged cellar from 1750 doing the traditional menu: flæskesteg, frikadeller, plaice, lunch and dinner.", hours: "Mon–Sat lunch & dinner (check Sun)" },
    "halvvejen": { name: "Café Halvvejen", lat: 55.68094, lng: 12.57392, kind: "food", addr: "Krystalgade 11", blurb: "Tiny old-school lunch café by the Round Tower. Generous smørrebrød, no fuss.", hours: "Lunch, roughly 11–16 (check)" },
    "hallernes": { name: "Hallernes Smørrebrød (Torvehallerne)", lat: 55.68387, lng: 12.56955, kind: "food", addr: "Torvehallerne, Frederiksborggade 21", blurb: "Counter smørrebrød in the food hall: point at two pieces, eat at the tables outside.", hours: "Hall hours (Sun 11–17)" },
    "paludan": { name: "Paludan Bogcafé", lat: 55.68033, lng: 12.57330, kind: "food", addr: "Fiolstræde 10", blurb: "Book café in the Latin Quarter with 90-kr plates, big brunches and students everywhere. Cheapest sit-down lunch in the centre.", hours: "Mon–Fri 09–22, Sat–Sun 10–22" },
    "riz-raz": { name: "Riz Raz", lat: 55.67706, lng: 12.57514, kind: "food", addr: "Kompagnistræde 20", blurb: "Mediterranean vegetarian buffet, eat as much as you like, meat skewers as add-ons. A budget classic since 1988.", hours: "Daily 11:30–24" },
    "sporvejen": { name: "Sporvejen", lat: 55.67946, lng: 12.57567, kind: "food", addr: "Gråbrødretorv 17", blurb: "Burgers and omelettes served inside an old tram carriage on the prettiest square in the old town.", hours: "Daily 11–22" },
    "dop": { name: "DØP pølsevogn", lat: 55.68118, lng: 12.57630, kind: "food", addr: "Købmagergade 52 (by the Round Tower)", blurb: "The organic hot-dog cart, sourdough buns, right under the Round Tower. The best 60 kr you'll spend.", hours: "Daily ≈11–18" },
    "johns-hotdog": { name: "John's Hotdog Deli", lat: 55.67361, lng: 12.56600, kind: "food", addr: "Bernstorffsgade 5", blurb: "Cart outside Tivoli/the station; regularly voted the best hot dog in the city. Try the 'French hot dog' too.", hours: "Daily ≈11–19" },
    "gasoline-grill": { name: "Gasoline Grill", lat: 55.68324, lng: 12.58517, kind: "food", addr: "Landgreven 10", blurb: "Burger stand in a former petrol station; they close when the day's patties run out (often by 16:00).", hours: "Daily 11–sold out" },
    "tommis": { name: "Tommi's Burger Joint", lat: 55.66827, lng: 12.55804, kind: "food", addr: "Høkerboderne 21", blurb: "Icelandic burger joint in Kødbyen. The 'offer' — burger, fries, soda — is the move.", hours: "Daily 11:30–21" },
    "warpigs": { name: "WarPigs Brewpub", lat: 55.66857, lng: 12.55989, kind: "food", addr: "Flæsketorvet 25", blurb: "Texas BBQ by the tray plus 22 taps of Mikkeller × 3 Floyds beer in a meat hall. Loud, fun, good value for meat.", hours: "Daily 11:30–22" },
    "mother": { name: "Mother", lat: 55.66858, lng: 12.55760, kind: "food", addr: "Høkerboderne 9-15", blurb: "Sourdough Neapolitan pizza in Kødbyen. Big tables, good for a group, kids fine.", hours: "Daily 11–23" },
    "slurp-ramen": { name: "Slurp Ramen Joint", lat: 55.68511, lng: 12.56718, kind: "food", addr: "Nansensgade 90", blurb: "The ramen place on cosy Nansensgade. Expect a short queue; it moves.", hours: "Tue–Sun 12–21ish, closed Mon" },
    "moller-kaffe": { name: "Møller Kaffe & Køkken", lat: 55.69575, lng: 12.54696, kind: "food", addr: "Nørrebrogade 160", blurb: "Nørrebro brunch: build your own plate from small dishes. Weekend queues, worth it.", hours: "Daily 07:30–15" },
    "dyrehaven-cafe": { name: "Dyrehaven", lat: 55.66566, lng: 12.54964, kind: "food", addr: "Sønder Boulevard 72", blurb: "Antlers on the walls, Danish-ish café food, cheap wine, Vesterbro locals. Brunch to late.", hours: "Daily 09–late" },
    "mad-og-kaffe": { name: "Mad & Kaffe", lat: 55.66594, lng: 12.55044, kind: "food", addr: "Sønder Boulevard 68", blurb: "Tick 3, 5 or 7 small brunch items on a card. Simple idea, always full.", hours: "Daily 08:30–17" },
    "absalon": { name: "Absalon", lat: 55.66539, lng: 12.55031, kind: "food", addr: "Sønder Boulevard 73", blurb: "A church turned people's house: fællesspisning (communal dinner) at 18:00 for ≈65 kr, then bingo, ping-pong, cheap bar.", hours: "Dinner 18:00 daily; tickets from 17:00" },
    "lagkagehuset-torvegade": { name: "Lagkagehuset (the original)", lat: 55.67249, lng: 12.59160, kind: "food", addr: "Torvegade 45", blurb: "The bakery chain started here in Christianshavn. Kanelsnegle, tebirkes, decent coffee.", hours: "Daily ≈06:30–19" },
    "hart-bageri": { name: "Hart Bageri", lat: 55.67538, lng: 12.54547, kind: "food", addr: "Gammel Kongevej 109", blurb: "Richard Hart's (ex-Tartine) bakery with Noma backing. Cardamom buns, croissants worth the walk.", hours: "Daily ≈07–17" },
    "meyers-bageri": { name: "Meyers Bageri", lat: 55.69186, lng: 12.54493, kind: "food", addr: "Jægersborggade 9", blurb: "Claus Meyer's original bakery. The kanelsnurre is the benchmark cinnamon bun.", hours: "Daily ≈07–18" },
    "juno-bakery": { name: "Juno the Bakery", lat: 55.70616, lng: 12.58169, kind: "food", addr: "Århusgade 48", blurb: "Tiny Østerbro bakery with a permanent queue for the cardamom bun. A pilgrimage; combine with Kastellet.", hours: "Wed–Sun ≈07:30–15" },
    "la-glace": { name: "Conditori La Glace", lat: 55.67859, lng: 12.57364, kind: "food", addr: "Skoubogade 3", blurb: "Copenhagen's oldest pastry shop (1870). Layer cakes under chandeliers; the Sportskage is the one.", hours: "Mon–Fri 08:30–18, Sat 09–18, Sun 10–18" },
    "coffee-collective-jaegersborggade": { name: "Coffee Collective", lat: 55.69366, lng: 12.54240, kind: "food", addr: "Jægersborggade 57", blurb: "The roastery that put Copenhagen on the coffee map. Filter coffee, tiny room, take it to the street.", hours: "Daily ≈07–19" },
    "host": { name: "Höst", lat: 55.68336, lng: 12.56617, kind: "food", addr: "Nørre Farimagsgade 41", blurb: "Nordic set menus in a rustic-design room; the accessible version of the New Nordic thing, and the go-to celebration dinner that doesn't cost a fortune.", hours: "Dinner daily from 17:30" },
    "vaekst": { name: "Vækst", lat: 55.67883, lng: 12.56718, kind: "food", addr: "Sankt Peders Stræde 34", blurb: "A greenhouse inside a restaurant. Vegetable-led Nordic menus, lovely for a special evening.", hours: "Dinner daily from 17:30, lunch Fri–Sun" },
    "mes": { name: "Restaurant Mes", lat: 55.67884, lng: 12.56642, kind: "food", addr: "Jarmers Plads 1", blurb: "Six-course tasting menu for the price of a main elsewhere. Small, warm, the best-value fine dining in the city.", hours: "Dinner Tue–Sat" },
    "baest": { name: "Bæst", lat: 55.69241, lng: 12.55625, kind: "food", addr: "Guldbergsgade 29", blurb: "Christian Puglisi's pizzeria with its own mozzarella and charcuterie. Book.", hours: "Dinner daily" },
    "fiskebar": { name: "Kødbyens Fiskebar", lat: 55.66788, lng: 12.55926, kind: "food", addr: "Flæsketorvet 100", blurb: "Seafood in a tiled meat hall with a fish tank at the bar. Oysters, mussels, the harbour on a plate.", hours: "Dinner daily, lunch Sat–Sun" },

    // Bars (not already listed above)
    "studenterhuset": { name: "Studenterhuset", lat: 55.68118, lng: 12.57630, kind: "bar", addr: "Købmagergade 52", blurb: "The university's student house, open to everyone: cheap draught, quiz nights, live music, ping-pong." },
    "kassen": { name: "Kassen", lat: 55.68798, lng: 12.56080, kind: "bar", addr: "Nørrebrogade 18", blurb: "Student party bar with the cheapest drinks in the city and the stickiest floor. Go late." },
    "kihoskh": { name: "Kihoskh", lat: 55.66648, lng: 12.55302, kind: "bar", addr: "Sønder Boulevard 53", blurb: "A kiosk with 400 beers, a bench outside and Sønder Boulevard's lawn opposite. The cheapest 'bar' in Vesterbro." },
    "nemoland": { name: "Nemoland", lat: 55.67299, lng: 12.59983, kind: "bar", addr: "Fabriksområdet 52, Christiania", blurb: "Christiania's big outdoor café-bar: cheap beer on long tables, free concerts on summer Sundays." },
    "eiffel-bar": { name: "Eiffel Bar", lat: 55.67406, lng: 12.59170, kind: "bar", addr: "Wildersgade 58", blurb: "Christianshavn bodega since 1736 with Eiffel-tower kitsch and neighbourhood regulars. Sailors' prices." },
    "bo-bi-bar": { name: "Bo-Bi Bar", lat: 55.68101, lng: 12.57869, kind: "bar", addr: "Klareboderne 14", blurb: "The tiniest, oldest-feeling bodega in the centre (1917): one room, red walls, writers and poets." },
    "blaagaards-apotek": { name: "Blågårds Apotek", lat: 55.68650, lng: 12.55787, kind: "bar", addr: "Blågårds Plads 2", blurb: "An old pharmacy turned music bar: jazz, folk or blues most nights, no cover, cheap beer." },
    "props": { name: "Props Coffee Shop", lat: 55.68764, lng: 12.55982, kind: "bar", addr: "Blågårdsgade 5", blurb: "Bar furnished with vintage pieces that are all for sale. Cheap bottles, candles, weekend DJs." },
    "harbo-bar": { name: "Harbo Bar", lat: 55.68794, lng: 12.55979, kind: "bar", addr: "Blågårdsgade 2D", blurb: "Nørrebro's easy-going corner bar: coffee by day, beer and DJs by night, tables on the street." },
    "palae-bar": { name: "Palæ Bar", lat: 55.68123, lng: 12.58371, kind: "bar", addr: "Ny Adelgade 5", blurb: "Jazz bodega behind Kongens Nytorv; journalists, actors, a soundtrack of vinyl. Five minutes from Nyhavn, half the price." },
    "hviids-vinstue": { name: "Hviids Vinstue", lat: 55.67983, lng: 12.58479, kind: "bar", addr: "Kongens Nytorv 19", blurb: "Copenhagen's oldest bar (1723), wood-panelled cellar rooms on Kongens Nytorv. Touristy but genuinely lovely; kitchen all day." },
    "charlies-bar": { name: "Charlie's Bar", lat: 55.68067, lng: 12.58029, kind: "bar", addr: "Pilestræde 33", blurb: "British real-ale pub with cask beers and a CAMRA award; football on, no music." },
    "bankeraat": { name: "Bankeråt", lat: 55.68337, lng: 12.56522, kind: "bar", addr: "Ahlefeldtsgade 29", blurb: "Taxidermy animals in costumes, brunch café by day, cheap-ish bar at night, near the Lakes." },
    "log-lady": { name: "The Log Lady", lat: 55.67828, lng: 12.56884, kind: "bar", addr: "Studiestræde 27", blurb: "Twin Peaks-themed bar in the old town: red curtains, cheap beers, a cocktail or two." },
    "lord-nelson": { name: "Lord Nelson", lat: 55.67797, lng: 12.57686, kind: "bar", addr: "Hyskenstræde 9", blurb: "Corner pub on a Strøget side street with Danish micro-brews on tap and outdoor seats." },
    "taphouse": { name: "Taphouse", lat: 55.67616, lng: 12.57148, kind: "bar", addr: "Lavendelstræde 15", blurb: "61 taps — the biggest tap wall in Denmark. Pricier per glass, but small pours let you try a lot." },
    "mesteren-laerlingen": { name: "Mesteren & Lærlingen", lat: 55.66773, lng: 12.55894, kind: "bar", addr: "Flæsketorvet 86", blurb: "Tiny Kødbyen dive with reggae and soul on the decks and people dancing on the tables by 01:00." },
    "jolene": { name: "Jolene", lat: 55.66733, lng: 12.56120, kind: "bar", addr: "Flæsketorvet 81-85", blurb: "Kødbyen's Berlin-ish party bar: free entry, cheap beer, DJs till 05:00 at weekends." },
    "bakken-kbh": { name: "Bakken", lat: 55.66869, lng: 12.55971, kind: "bar", addr: "Flæsketorvet 19-21", blurb: "Club-bar in the meat market: cheap draught, loud, free before midnight." },
    "fermentoren": { name: "Fermentoren", lat: 55.66789, lng: 12.55648, kind: "bar", addr: "Halmtorvet 29C", blurb: "Craft-beer cellar on Halmtorvet with 20+ taps and a candle-lit courtyard." },
    "mikkeller-bar": { name: "Mikkeller Bar", lat: 55.67196, lng: 12.55755, kind: "bar", addr: "Viktoriagade 8B-C", blurb: "The original Mikkeller bar in a Vesterbro basement. Not cheap; one beer here is the pilgrimage." },
    "vinstue-90": { name: "Vinstue 90", lat: 55.67517, lng: 12.54768, kind: "bar", addr: "Gammel Kongevej 90", blurb: "Home of the 'slow beer': a Carlsberg poured over 10–15 minutes from a wooden barrel. Bodega perfection." },
    "olbaren": { name: "Ølbaren", lat: 55.68937, lng: 12.55800, kind: "bar", addr: "Elmegade 2", blurb: "Beer-nerd bar on Elmegade with 100+ bottles and a knowledgeable bartender. Pricier, but the list is the point." },
    "brus": { name: "BRUS", lat: 55.69187, lng: 12.55578, kind: "bar", addr: "Guldbergsgade 29F", blurb: "To Øl's brewpub in an old iron foundry: 30 taps, a bottle shop, pizza-ish food." },
    "norrebro-bryghus": { name: "Nørrebro Bryghus", lat: 55.69025, lng: 12.56397, kind: "bar", addr: "Ryesgade 3", blurb: "Copenhagen's first brewpub (2003), by the Lakes. Happy hour before 18:00." },
    "orsted-olbar": { name: "Ørsted Ølbar", lat: 55.68139, lng: 12.56457, kind: "bar", addr: "Nørre Farimagsgade 13", blurb: "Small craft bar on a quiet street by Ørstedsparken; comfy, cheap-ish for craft." },

    // Defence day
    "dtu-building-101": { name: "DTU Lyngby · Building 101", lat: 55.78585, lng: 12.52144, kind: "sight", addr: "Anker Engelunds Vej 1, Kongens Lyngby", blurb: "Main building of the DTU campus — the defence room is nearby. Change the building in data.js if it's elsewhere.", cost: "" },
    "dtu-bus-stop": { name: "Rævehøjvej (DTU) bus stop", lat: 55.78765, lng: 12.53148, kind: "transit", addr: "Rævehøjvej, Kongens Lyngby", blurb: "15E and 150S stop on the motorway edge of campus, 8 minutes' walk from Building 101.", cost: "≈30–38 kr to Nørreport" },
    "lyngby-station": { name: "Lyngby Station", lat: 55.76803, lng: 12.50478, kind: "transit", blurb: "S-train to Nørreport (≈18 min). Bus 300S/ 30E link campus and the station.", cost: "" },
    "airport": { name: "Copenhagen Airport (Lufthavnen metro)", lat: 55.63091, lng: 12.64922, kind: "transit", addr: "Terminal 3, Kastrup", blurb: "Metro M2 arrives straight into Terminal 3. From Kongens Nytorv 15 min, from Nørreport 17 min, trains run every 4–6 min.", cost: "30 kr (3 zones)" },

    // Day trips
    "louisiana": { name: "Louisiana Museum of Modern Art", lat: 55.96935, lng: 12.54316, kind: "sight", addr: "Gl. Strandvej 13, Humlebæk", blurb: "Modern art in a garden on the Øresund shore. Regularly called the best museum in the world; the setting is half of it." },
    "kronborg": { name: "Kronborg Castle (Hamlet's Elsinore)", lat: 56.03905, lng: 12.62121, kind: "sight", addr: "Helsingør", blurb: "Renaissance fortress on the narrowest point of the Sound, Shakespeare's Elsinore. Sweden is 4 km across the water." },
    "roskilde-domkirke": { name: "Roskilde Cathedral", lat: 55.64264, lng: 12.08043, kind: "sight", addr: "Roskilde", blurb: "UNESCO brick cathedral where 40 Danish kings and queens are buried." },
    "viking-ship-museum": { name: "Viking Ship Museum", lat: 55.65087, lng: 12.08147, kind: "sight", addr: "Roskilde", blurb: "Five real Viking ships raised from the fjord, and reconstructions you can sail in summer." },
    "bakken": { name: "Dyrehaven & Bakken", lat: 55.77468, lng: 12.57775, kind: "sight", addr: "Klampenborg", blurb: "Royal deer park with 2,000 deer and the Eremitage palace; next to Bakken, the world's oldest amusement park (free entry)." },
  },

  // --------------------------------------------------------------- TOURS ----
  tours: [
    {
      id: "l1", num: 1, colorName: "Red line", name: "The Postcard", short: "Postcard",
      tagline: "Nyhavn, the palaces, the fortress and the Mermaid. Every picture you've seen of Copenhagen, in one gentle loop along the water.",
      km: "4.5 km", hours: "4–5 h", budget: "0–150 kr", best: "First day", startEnd: "Kongens Nytorv → Østerport",
      pace: "Flat, mostly car-free. Lunch at the harbour end of Nyhavn after the guard change, then the green stretch north.",
      stops: [
        { place: "kongens-nytorv", note: "Start at the metro exit. Look at the equestrian statue, the theatre, and the world's most photographed hotel front, then walk into Nyhavn." },
        { place: "nyhavn", minutes: 30 },
        { place: "inderhavnsbroen", optional: true, note: "Two-minute detour onto the bridge for the Opera view; come straight back." },
        { place: "amalienborg", minutes: 25, note: "Be here by 11:50 for the 12:00 changing of the guard. If you're later, just enjoy the square — the guards stand there all day." },
        { place: "marble-church", minutes: 20 },
        { place: "told-snaps", eat: true, note: "Lunch. Two or three pieces of smørrebrød each, one snaps for the table. Reserve if it's a weekend.", tip: "Cheaper alternative: pick up sandwiches at Torvehallerne beforehand and eat on the Kastellet ramparts." },
        { place: "designmuseum", optional: true, note: "If it's raining or you like chairs." },
        { place: "nyboder", optional: true, note: "Five-minute detour west on the way to Kastellet." },
        { place: "kastellet", minutes: 30 },
        { place: "gefion", minutes: 10 },
        { place: "little-mermaid", minutes: 15 },
        { place: "osterport", transit: true, note: "Finish here (S-train to Nørreport, 2 stops) — or walk back down Bredgade past the Marble Church in 30 minutes and end with a beer at Palæ Bar or Hviids Vinstue." },
      ],
      tips: [
        "<b>Timing:</b> start 10:30 to catch the 12:00 guard change with time for Nyhavn first. Starting after lunch also works — just drop Amalienborg's guard change.",
        "<b>Evening add-on:</b> Palæ Bar (jazz bodega) or Hviids Vinstue (1723) are 5 minutes from Nyhavn and half the price of anything on the quay.",
        "<b>Rain plan:</b> Designmuseum Danmark or the Amalienborg museum swap in for Kastellet.",
      ],
    },
    {
      id: "l2", num: 2, colorName: "Cyan line", name: "Harbour & Christianshavn", short: "Harbour",
      tagline: "Power, parliament and a free tower, then across the bridge to canals, a corkscrew spire and the freetown.",
      km: "5 km", hours: "4.5–5.5 h", budget: "0–200 kr", best: "Sunday afternoon", startEnd: "Gammel Strand → Nyhavn",
      pace: "One climb (the spire, optional). Lots of benches by the water. Christiania is the wildcard — give it an hour.",
      stops: [
        { place: "gammel-strand", note: "Start at the metro exit by the canal. The view across to Christiansborg is the opener." },
        { place: "christiansborg", minutes: 45, note: "Go up the free tower first (closed Mondays), then decide about the reception rooms." },
        { place: "thorvaldsens", optional: true },
        { place: "black-diamond", minutes: 15, note: "Walk through the atrium to the harbour side and sit on the steps." },
        { place: "borsen", minutes: 5 },
        { place: "knippelsbro", minutes: 5 },
        { place: "christianshavn-torv", minutes: 25, note: "Coffee and a kanelsnegl at the original Lagkagehuset on Torvegade, then wander the canal streets." },
        { place: "our-saviour", minutes: 45, note: "Climb it if the weather's calm and nobody minds heights. Otherwise the church is free and worth five minutes." },
        { place: "christiania-main", minutes: 60 },
        { place: "morgenstedet", eat: true, note: "Cheap vegetarian lunch inside Christiania (closed Mondays). Or hold out for the next stop.", tip: "Nemoland, next door, is the cheap-beer garden." },
        { place: "broens-gadekokken", eat: true, note: "Street-food stalls on the quay — late lunch or an early dinner, with a beer on the edge of the water." },
        { place: "inderhavnsbroen", minutes: 10, note: "Cross the Kissing Bridge back to Nyhavn: the best angle on the coloured houses is from this side." },
        { place: "nyhavn", note: "End. Kongens Nytorv metro is 3 minutes away." },
      ],
      tips: [
        "<b>Extend it:</b> from the Black Diamond, walk 12 minutes south to Islands Brygge harbour bath and Kalvebod Bølge before crossing Knippelsbro.",
        "<b>Christiania rules:</b> no photos in the central Green Light District, no running (it startles people), cash helps. The rest of Christiania is relaxed and family-friendly.",
        "<b>Sunday note:</b> Christiansborg's tower closes at 17:30 on Sundays and is closed Mondays — do this line Saturday or Sunday.",
      ],
    },
    {
      id: "l3", num: 3, colorName: "Amber line", name: "Old Town & Latin Quarter", short: "Old Town",
      tagline: "City Hall to the King's Garden through the medieval core: the walking street, the cathedral quarter, a tower you climb without stairs, a food hall and a palm house.",
      km: "4 km", hours: "4–5 h", budget: "60–200 kr", best: "Sunday morning", startEnd: "Rådhuspladsen → Nørreport",
      pace: "The shortest line and the most stop-start. Everything is 5 minutes from the last thing.",
      stops: [
        { place: "radhuspladsen", minutes: 15, note: "Start under the City Hall clock. Tivoli's gates are across the road (closed this week)." },
        { place: "gammeltorv", minutes: 20, note: "Walk Strøget as far as Gammeltorv/Nytorv, then turn left into the Latin Quarter." },
        { place: "vor-frue-kirke", minutes: 20 },
        { place: "graabrodretorv", minutes: 10 },
        { place: "paludan", eat: true, optional: true, note: "Cheap early lunch or a coffee among the bookshelves, if it's that time." },
        { place: "round-tower", minutes: 30, note: "Walk the spiral ramp to the roof. Buy tickets at the door; it rarely queues long." },
        { place: "dop", eat: true, note: "Hot dog from the organic cart under the tower. Order 'ristet med det hele' — toasted with everything." },
        { place: "stroget-amagertorv", minutes: 20, note: "Back onto Strøget at its grandest stretch. Illum's rooftop is a free lift ride to a view." },
        { place: "rosenborg", minutes: 60, note: "Crown Jewels if you booked; otherwise the garden, the barracks and the view of the castle across the moat are free." },
        { place: "torvehallerne", eat: true, note: "Lunch, properly: Hallernes smørrebrød, Grød porridge or Hija de Sanchez tacos, eaten at the tables between the halls." },
        { place: "botanical-garden", minutes: 30, note: "Climb the spiral stairs inside the Palm House. Then find a bench by the lake." },
        { place: "orstedsparken", optional: true },
        { place: "norreport", transit: true, note: "End at Nørreport — metro, trains, or 10 minutes' walk back to the centre. Line 4 starts exactly here." },
      ],
      tips: [
        "<b>Pair it:</b> Line 3 in the morning, lunch at Torvehallerne, then Line 2 or Line 4 in the afternoon is the classic full day.",
        "<b>Rosenborg</b> sells out at weekends — book the timed ticket the night before or skip it and keep 140 kr for dinner.",
        "<b>Sunday shopping:</b> most shops on Strøget open Sundays 11–17; smaller ones don't.",
      ],
    },
    {
      id: "l4", num: 4, colorName: "Green line", name: "Nørrebro & the Lakes", short: "Nørrebro",
      tagline: "Where the city actually lives: a cemetery-park with famous graves, the coolest street, a park made of 60 countries, a legendary kebab and the cheapest bars in town.",
      km: "5 km", hours: "3.5–4.5 h", budget: "60–150 kr", best: "Afternoon → evening", startEnd: "Nørreport → Blågårds Plads",
      pace: "Flat and easy. Start after lunch so it ends at bar o'clock, or start mid-morning and make Grød the brunch.",
      stops: [
        { place: "norreport", note: "Start at Nørreport and walk west along Frederiksborggade to the Lakes." },
        { place: "torvehallerne", eat: true, optional: true, note: "Breakfast pastries if you haven't eaten." },
        { place: "dronning-louises-bro", minutes: 15, note: "Stand in the middle for the classic Lakes view; note it for a sunset beer later." },
        { place: "assistens", minutes: 40 },
        { place: "jaegersborggade", minutes: 30, note: "Walk the whole street. Ceramics at the top end, Meyers bakery near the bottom, Coffee Collective for the coffee." },
        { place: "grod-jaegersborggade", eat: true, note: "Porridge lunch — sounds austere, is delicious." },
        { place: "superkilen", minutes: 20 },
        { place: "kebabistan", eat: true, note: "The famous durum for the walk back — or save it for late night." },
        { place: "elmegade", minutes: 15 },
        { place: "blaagaards-plads", minutes: 15, note: "End here: Props, Harbo Bar and Blågårds Apotek are all on the square. Nørreport is a 10-minute walk when you're done." },
      ],
      tips: [
        "<b>The local move:</b> buy beers at the Netto on Nørrebrogade and drink them on Dronning Louises Bro at sunset (≈19:00 in late September). Legal, and what everyone else is doing.",
        "<b>Brunch version:</b> start at Møller Kaffe & Køkken (Nørrebrogade 160), then do the line backwards.",
        "<b>Music:</b> Blågårds Apotek has live jazz/folk most nights, no cover.",
      ],
    },
    {
      id: "l5", num: 5, colorName: "Violet line", name: "Vesterbro, Meatpacking & Carlsberg", short: "Vesterbro",
      tagline: "The rough-turned-cool side of town: an art museum with a palm garden, a meat market full of restaurants, Little Paris, the elephants of Carlsberg and a romantic garden.",
      km: "6 km", hours: "5–6 h", budget: "0–350 kr", best: "Any day but Monday", startEnd: "Central Station → Frederiksberg Allé",
      pace: "The longest line. Two natural exits: Enghave Plads metro (after Kødbyen) or the Elephant Gate.",
      stops: [
        { place: "central-station", note: "Start under the wooden roof of the main hall." },
        { place: "tivoli", minutes: 10 },
        { place: "glyptotek", optional: true, note: "Free on Tuesdays, closed Mondays. The Winter Garden café is worth the ticket on its own." },
        { place: "kodbyen", minutes: 30 },
        { place: "hija-de-sanchez", eat: true, note: "Tacos for lunch. Alternatives 50 m away: WarPigs (BBQ), Tommi's (burgers), Mother (pizza) — all group-friendly.", tip: "Kødbyen is also where Line 5 turns into a night: Jolene, Mesteren & Lærlingen, Bakken." },
        { place: "istedgade", minutes: 20 },
        { place: "vaernedamsvej", minutes: 20, note: "Coffee at Granola, cheese at the fromagerie, a look in the wine bars." },
        { place: "enghave-plads", transit: true, note: "Metro M3 if legs are done. Otherwise: 15 minutes west to the elephants." },
        { place: "carlsberg-elephant-gate", minutes: 20 },
        { place: "home-of-carlsberg", optional: true },
        { place: "cisternerne", optional: true },
        { place: "frederiksberg-have", minutes: 45 },
        { place: "frederiksberg-alle-st", transit: true, note: "End: metro M3, 6 minutes back to the centre. Or walk Gammel Kongevej back (Hart Bageri, Vinstue 90's slow beer)." },
      ],
      tips: [
        "<b>Cheap dinner trick:</b> Absalon on Sønder Boulevard serves a communal two-course dinner at 18:00 for about 65 kr — buy the ticket at the bar from 17:00, sit with strangers, stay for bingo.",
        "<b>Tivoli is closed</b> 21 Sep–1 Oct 2026 (between the summer and Halloween seasons). If you're back in October, this line becomes an evening line ending inside the park.",
        "<b>Monday warning:</b> the Glyptotek, Cisternerne and most museums are closed on Mondays.",
      ],
    },
    {
      id: "l6", num: 6, colorName: "Pink line", name: "By Water", short: "Water",
      tagline: "The least walking, the most seeing: a canal boat under the bridges, a public-transport ferry to the old shipyard, street food on the quay and a hike up a power plant.",
      km: "3.5 km walking", hours: "4–5 h", budget: "125–250 kr", best: "Sunny afternoon", startEnd: "Holmens Kirke → Nordre Toldbod",
      pace: "Sit down on a boat, twice. Ideal for tired legs or a day when everyone wants to chill.",
      stops: [
        { place: "holmens-kirke", transit: true, note: "Netto-Bådene one-hour canal tour: Little Mermaid, the Opera, Christianshavn's canals, the Black Diamond, all from the water, for about 100 kr (Stromma charges ≈130+ for the same route). Boats also leave from Nyhavn.", tip: "Sit on the left side leaving Holmens Kirke for the Mermaid and Opera; duck for the low bridges." },
        { place: "nyhavn", minutes: 10, note: "Walk 10 minutes along the Havnegade waterfront to the Nyhavn harbour-bus stop (by the bridge)." },
        { place: "refshaleoen-stop", transit: true, note: "Harbour bus 991/992 northbound to Refshaleøen (≈15 min, every 20–30 min). It's a regular bus ticket — 2 zones, 24 kr — and a better boat ride than most tours." },
        { place: "reffen", eat: true, note: "Lunch on the quay. Confirm on reffen.dk that the season is still on this weekend; if not, La Banchina or Lille Bakery." },
        { place: "la-banchina", eat: true, optional: true, note: "A glass of wine on the swimming pier." },
        { place: "lille-bakery", eat: true, optional: true },
        { place: "copenhagen-contemporary", optional: true },
        { place: "copenhill", minutes: 45, note: "15-minute walk south. Take the lift up, walk down the roof trail; rooftop bar at the top." },
        { place: "nordre-toldbod", transit: true, note: "Walk back to the Refshaleøen stop and take the harbour bus south to Nordre Toldbod — you land next to Kastellet and the Mermaid — or ride on to Nyhavn." },
      ],
      tips: [
        "<b>Harbour buses</b> 991/992 run roughly 07–19 on weekdays and 10–19 at weekends; check the Rejseplanen app for the next departure.",
        "<b>CopenHill</b> closes 17:00 on Sundays, 19:00 other days.",
        "<b>Skip the canal tour</b> if money's tight — the harbour bus alone covers half the same water for a quarter of the price.",
      ],
    },
  ],

  bonus: [
    { place: "islands-brygge-havnebad", near: "Line 2 · 12 min from the Black Diamond" },
    { place: "kalvebod-bolge", near: "Line 2 · opposite Islands Brygge" },
    { place: "cykelslangen", near: "Line 5 · 10 min from Kødbyen" },
    { place: "blox", near: "Line 2 · between Christiansborg and the Black Diamond" },
    { place: "stroget-illum", near: "Line 3 · on Amagertorv" },
    { place: "nyboder", near: "Line 1 · between the Marble Church and Kastellet" },
    { place: "opera", near: "Line 6 · from the harbour bus" },
    { place: "zoo", near: "Line 5 · next to Frederiksberg Have" },
    { place: "juno-bakery", near: "Line 1 · 15 min north of Kastellet (Wed–Sun)" },
  ],

  daytrips: [
    { name: "Louisiana Museum of Modern Art", blurb: "Art, sculpture park and the sea, 35 km north. The single best day trip if you have one.", how: "Train Nørreport → Humlebæk, 35 min + 10 min walk", cost: "≈170 kr entry · closed Mon", time: "Half day", link: "https://www.google.com/maps/search/?api=1&query=Louisiana%20Museum%20of%20Modern%20Art" },
    { name: "Kronborg & Helsingør", blurb: "Hamlet's castle, the maritime museum sunk into a dry dock, and a 20-minute ferry to Sweden for the fun of it.", how: "Train Nørreport → Helsingør, 45 min", cost: "≈160 kr castle", time: "Half day — combine with Louisiana", link: "https://www.google.com/maps/search/?api=1&query=Kronborg%20Slot" },
    { name: "Roskilde", blurb: "Royal tombs in a UNESCO cathedral and five real Viking ships on the fjord.", how: "Train from Central Station, 25 min", cost: "Cathedral ≈70 kr · Viking Ship Museum ≈170 kr", time: "Half day", link: "https://www.google.com/maps/search/?api=1&query=Vikingeskibsmuseet%20Roskilde" },
    { name: "Dyrehaven & Bakken", blurb: "A royal deer park with 2,000 deer and the world's oldest amusement park next door — 20 minutes from town, and 10 from DTU.", how: "S-train C → Klampenborg, 25 min", cost: "Free (Bakken rides extra)", time: "2–4 h", link: "https://www.google.com/maps/search/?api=1&query=Dyrehaven%20Klampenborg" },
    { name: "Malmö, Sweden", blurb: "Over the Øresund bridge for lunch in another country. Old town, the Turning Torso, cheaper beer.", how: "Train from Central/Nørreport, 35–40 min", cost: "≈120 kr each way · bring passport/ID", time: "Half day", link: "https://www.google.com/maps/search/?api=1&query=Lilla%20Torg%20Malm%C3%B6" },
  ],

  // --------------------------------------------------------- RESTAURANTS ----
  // price: 1 cheap (<120), 2 mid (120–250), 3 splurge (250+). avg = typical spend per person, used for sorting.
  restaurants: [
    { place: "dop", type: "Hot dogs", area: "Indre By", price: 1, avg: 60, priceLabel: "≈60 kr", tryThis: "'Ristet med det hele' — toasted, with remoulade, mustard, crispy and raw onions, pickles", hours: "Daily ≈11–18" },
    { place: "johns-hotdog", type: "Hot dogs", area: "Vesterbro", price: 1, avg: 60, priceLabel: "≈50–70 kr", tryThis: "Classic hot dog, then a French hot dog (sausage in a hollow baguette)", hours: "Daily ≈11–19" },
    { place: "kebabistan", type: "Kebab", area: "Nørrebro", price: 1, avg: 65, priceLabel: "≈65 kr", tryThis: "Durum kebab, medium-spicy, with garlic sauce", hours: "Daily ≈11–late" },
    { place: "absalon", type: "Communal dinner", area: "Vesterbro", price: 1, avg: 65, priceLabel: "≈65 kr", tryThis: "Whatever's on — two courses, one table of strangers", hours: "18:00 daily, tickets at the bar from 17:00", flag: "Best value" },
    { place: "grod-jaegersborggade", type: "Porridge / café", area: "Nørrebro", price: 1, avg: 80, priceLabel: "≈60–95 kr", tryThis: "Oat porridge with dulce de leche, apple and roasted almonds; or the daily risotto", hours: "Daily ≈07:30–21" },
    { place: "hallernes", type: "Smørrebrød", area: "Indre By", price: 1, avg: 90, priceLabel: "≈60–100 kr/piece", tryThis: "Marinated herring on rye + roast beef with remoulade", hours: "Torvehallerne hours (Sun 11–17)" },
    { place: "paludan", type: "Café", area: "Indre By", price: 1, avg: 95, priceLabel: "≈80–110 kr", tryThis: "The Paludan plate or a burger — portions are student-sized", hours: "Mon–Fri 09–22, Sat–Sun 10–22" },
    { place: "gasoline-grill", type: "Burgers", area: "Indre By", price: 1, avg: 95, priceLabel: "≈95 kr", tryThis: "Butter burger + fries. Go before 15:00 or they're sold out", hours: "Daily 11–sold out" },
    { place: "riz-raz", type: "Vegetarian buffet", area: "Indre By", price: 1, avg: 110, priceLabel: "≈100–130 kr", tryThis: "The buffet (lunch is cheaper than dinner); lamb skewer on the side if you must", hours: "Daily 11:30–24" },
    { place: "sporvejen", type: "Burgers", area: "Indre By", price: 1, avg: 110, priceLabel: "≈90–130 kr", tryThis: "Burger and a beer, sitting in the old tram", hours: "Daily 11–22" },
    { place: "morgenstedet", type: "Vegetarian", area: "Christianshavn", price: 1, avg: 110, priceLabel: "≈100–120 kr", tryThis: "The daily plate plus a slice of the cake", hours: "Tue–Sun 12–21", flag: "Mon closed" },
    { place: "broens-gadekokken", type: "Street food", area: "Nyhavn", price: 1, avg: 110, priceLabel: "≈90–140 kr", tryThis: "Pick a stall, grab a beer, eat on the quay edge", hours: "Season Mar–Oct ≈11–21" },
    { place: "reffen", type: "Street food", area: "Refshaleøen", price: 1, avg: 110, priceLabel: "≈90–150 kr", tryThis: "Anything off a grill; eat on the quay facing the city", hours: "≈11:30–21:30 in season — check reffen.dk", flag: "Check season" },
    { place: "tommis", type: "Burgers", area: "Vesterbro", price: 1, avg: 115, priceLabel: "≈100–130 kr", tryThis: "The 'offer': burger, fries and a soda", hours: "Daily 11:30–21" },
    { place: "lagkagehuset-torvegade", type: "Bakery", area: "Christianshavn", price: 1, avg: 45, priceLabel: "≈35–55 kr", tryThis: "Kanelsnegl or tebirkes with a coffee", hours: "Daily ≈06:30–19" },
    { place: "meyers-bageri", type: "Bakery", area: "Nørrebro", price: 1, avg: 40, priceLabel: "≈35–50 kr", tryThis: "Kanelsnurre (cinnamon twist)", hours: "Daily ≈07–18" },
    { place: "hart-bageri", type: "Bakery", area: "Frederiksberg", price: 1, avg: 45, priceLabel: "≈40–60 kr", tryThis: "Cardamom bun and a 'Hart' croissant", hours: "Daily ≈07–17" },
    { place: "juno-bakery", type: "Bakery", area: "Østerbro", price: 1, avg: 45, priceLabel: "≈40–55 kr", tryThis: "Kardemommesnurre — the cardamom bun that started the queue", hours: "Wed–Sun ≈07:30–15", flag: "Mon–Tue closed" },
    { place: "lille-bakery", type: "Bakery / café", area: "Refshaleøen", price: 1, avg: 70, priceLabel: "≈50–120 kr", tryThis: "Whatever's on the counter; the lunch plates are big", hours: "Wed–Sun ≈08–15" },
    { place: "coffee-collective-jaegersborggade", type: "Coffee", area: "Nørrebro", price: 1, avg: 45, priceLabel: "≈40–55 kr", tryThis: "A filter coffee — they roast next door", hours: "Daily ≈07–19" },
    { place: "hija-de-sanchez", type: "Tacos", area: "Vesterbro", price: 2, avg: 150, priceLabel: "≈45–60 kr/taco", tryThis: "Three tacos (al pastor, carnitas, whatever's special) and a horchata", hours: "Tue–Sun ≈12–21", flag: "Mon closed" },
    { place: "mother", type: "Pizza", area: "Vesterbro", price: 2, avg: 150, priceLabel: "≈120–170 kr", tryThis: "Sourdough pizza to share, burrata to start", hours: "Daily 11–23" },
    { place: "dyrehaven-cafe", type: "Brunch / café", area: "Vesterbro", price: 2, avg: 150, priceLabel: "≈120–180 kr", tryThis: "Brunch plate by day, the burger and cheap wine by night", hours: "Daily 09–late" },
    { place: "mad-og-kaffe", type: "Brunch / café", area: "Vesterbro", price: 2, avg: 160, priceLabel: "≈130–180 kr", tryThis: "Five items on the brunch card — the chia and the sausage are the popular picks", hours: "Daily 08:30–17" },
    { place: "moller-kaffe", type: "Brunch / café", area: "Nørrebro", price: 2, avg: 160, priceLabel: "≈130–190 kr", tryThis: "Build a brunch plate: the pancakes and the cheese are the ones people order twice", hours: "Daily 07:30–15" },
    { place: "slurp-ramen", type: "Ramen", area: "Indre By", price: 2, avg: 160, priceLabel: "≈150–180 kr", tryThis: "Shoyu ramen with the extra egg", hours: "Tue–Sun ≈12–21", flag: "Mon closed" },
    { place: "halvvejen", type: "Traditional Danish", area: "Indre By", price: 2, avg: 160, priceLabel: "≈120–200 kr", tryThis: "Stegt flæsk, or two pieces of smørrebrød and a beer", hours: "Lunch ≈11–16 (check)" },
    { place: "cafe-sorgenfri", type: "Traditional Danish", area: "Indre By", price: 2, avg: 180, priceLabel: "≈150–230 kr", tryThis: "Stegt flæsk med persillesovs — all-you-can-eat crispy pork belly with parsley sauce", hours: "Daily ≈11–21, kitchen all day", flag: "Open all day" },
    { place: "kanal-cafeen", type: "Smørrebrød", area: "Indre By", price: 2, avg: 200, priceLabel: "≈150–250 kr", tryThis: "'Sol over Gudhjem': smoked herring, raw egg yolk, radish, chives", hours: "Mon–Fri 11:30–17, Sat 11:30–15", flag: "Sun closed" },
    { place: "kronborg-restaurant", type: "Smørrebrød", area: "Indre By", price: 2, avg: 200, priceLabel: "≈150–250 kr", tryThis: "Breaded plaice with remoulade, then 'dyrlægens natmad' (liver pâté, salt beef, aspic)", hours: "Mon–Sat ≈11–17", flag: "Sun closed" },
    { place: "slotskaelderen", type: "Smørrebrød", area: "Indre By", price: 2, avg: 200, priceLabel: "≈150–250 kr", tryThis: "Herring, then the tartar; point at the counter", hours: "Tue–Sat 11–15", flag: "Sun–Mon closed" },
    { place: "restaurant-puk", type: "Traditional Danish", area: "Indre By", price: 2, avg: 220, priceLabel: "≈180–280 kr", tryThis: "Frikadeller with red cabbage, or the roast pork with crackling", hours: "Mon–Sat lunch & dinner" },
    { place: "told-snaps", type: "Smørrebrød", area: "Nyhavn", price: 2, avg: 220, priceLabel: "≈180–260 kr", tryThis: "Two–three pieces (herring → fried plaice → roast beef) and a flight of snaps", hours: "Daily 11:30–16:00" },
    { place: "warpigs", type: "BBQ", area: "Vesterbro", price: 2, avg: 200, priceLabel: "≈150–250 kr", tryThis: "Brisket by weight, two sides, a Mikkeller × 3 Floyds beer", hours: "Daily 11:30–22" },
    { place: "la-banchina", type: "Café / wine", area: "Refshaleøen", price: 2, avg: 150, priceLabel: "≈100–200 kr", tryThis: "Fish of the day and a glass of natural wine, feet on the pier", hours: "Daily ≈09–22 (check)" },
    { place: "la-glace", type: "Cake", area: "Indre By", price: 2, avg: 120, priceLabel: "≈90–150 kr", tryThis: "Sportskage (choux, macaroon, cream) with hot chocolate", hours: "Mon–Fri 08:30–18, Sat 09–18, Sun 10–18" },
    { place: "aamanns-1921", type: "Smørrebrød", area: "Indre By", price: 3, avg: 320, priceLabel: "≈250–400 kr", tryThis: "The three-piece lunch, or tarteletter if they're on", hours: "Lunch daily 11:30–17 (last order 16:00), dinner 17:30–22:30", flag: "Book" },
    { place: "schonnemann", type: "Smørrebrød", area: "Indre By", price: 3, avg: 350, priceLabel: "≈300–450 kr", tryThis: "Herring three ways to start, fried plaice, the 'Schønnemann' beef tartare, snaps", hours: "Mon–Sat 11:30–17:00", flag: "Book · Sun closed" },
    { place: "baest", type: "Pizza", area: "Nørrebro", price: 3, avg: 350, priceLabel: "≈300–400 kr", tryThis: "House charcuterie, burrata, two pizzas between three", hours: "Dinner daily", flag: "Book" },
    { place: "vaekst", type: "Nordic", area: "Indre By", price: 3, avg: 450, priceLabel: "≈400–500 kr", tryThis: "The 4-course 'green' menu in the greenhouse", hours: "Dinner from 17:30, lunch Fri–Sun", flag: "Book" },
    { place: "host", type: "Nordic", area: "Indre By", price: 3, avg: 500, priceLabel: "≈450–550 kr", tryThis: "The 3-course menu with the 'snacks' add-on", hours: "Dinner daily from 17:30", flag: "Book" },
    { place: "fiskebar", type: "Seafood", area: "Vesterbro", price: 3, avg: 500, priceLabel: "≈400–600 kr", tryThis: "Oysters, then blue mussels in cider", hours: "Dinner daily, lunch Sat–Sun", flag: "Book" },
    { place: "mes", type: "Nordic", area: "Indre By", price: 3, avg: 550, priceLabel: "≈500–600 kr", tryThis: "The 6-course tasting menu — the value surprise of the city", hours: "Dinner Tue–Sat", flag: "Book" },
  ],
  eatTip: "Lunch is the cheap meal here: smørrebrød and the traditional dishes are lunch things, and most classic Danish places close at 16–17. Dinner for a group is where Copenhagen gets expensive — do street food (Broens, Reffen), Kødbyen, or Absalon's 65-kr communal dinner. Tap water is free and excellent — ask for <b>postevand</b>. No tipping expected; round up if you liked it.",

  // ---------------------------------------------------------------- BARS ----
  bars: [
    { place: "kihoskh", area: "Vesterbro", vibe: "Beer kiosk + lawn", beer: "≈20–40 kr", avg: 30, hours: "Daily till late", blurb: "400 beers in fridges, a bench outside and Sønder Boulevard's grass across the road. The cheapest 'bar' in Vesterbro." },
    { place: "dronning-louises-bro", area: "Nørrebro", vibe: "Bridge at sunset", beer: "≈12–20 kr (Netto)", avg: 16, hours: "Always", blurb: "Not a bar. Buy a Tuborg at the supermarket and sit on the bridge over the Lakes with everybody else — sunset is ≈19:00 in late September." },
    { place: "nyhavn", area: "Nyhavn", vibe: "Pier edge", beer: "≈15–25 kr (kiosk)", avg: 20, hours: "Always", blurb: "Also not a bar. Legs over the edge of the quay with a kiosk beer, looking at the same houses the terraces charge 75 kr to look at." },
    { place: "kassen", area: "Nørrebro", vibe: "Student party bar", beer: "≈25–35 kr", avg: 30, hours: "Nightly from ≈20", blurb: "Cheapest drinks in the city, 2-for-1 shots, sticky floor, very loud. You'll know within a minute if it's your night." },
    { place: "studenterhuset", area: "Indre By", vibe: "Student house", beer: "≈30–40 kr", avg: 35, hours: "Mon–Sat, closed Sun", blurb: "By the Round Tower, run by the university, open to all: cheap draught, quiz nights, live music, ping-pong." },
    { place: "absalon", area: "Vesterbro", vibe: "Community house", beer: "≈30–40 kr", avg: 35, hours: "Daily till 24", blurb: "The church-turned-people's-house: cheap bar, ping-pong, bingo, and the 65-kr communal dinner at 18:00." },
    { place: "nemoland", area: "Christianshavn", vibe: "Christiania garden", beer: "≈35–45 kr", avg: 40, hours: "Daily", blurb: "Long tables outdoors in the freetown; free concerts on summer Sundays." },
    { place: "eiffel-bar", area: "Christianshavn", vibe: "Bodega", beer: "≈35–45 kr", avg: 40, hours: "Daily 11–late", blurb: "1736 neighbourhood bodega with Paris kitsch and regulars. Sailors' prices." },
    { place: "blaagaards-apotek", area: "Nørrebro", vibe: "Live music bodega", beer: "≈40–45 kr", avg: 42, hours: "Daily from ≈14", blurb: "Jazz, folk or blues most nights on a tiny stage, no cover charge." },
    { place: "props", area: "Nørrebro", vibe: "Vintage-furniture bar", beer: "≈40–50 kr", avg: 45, hours: "Daily", blurb: "Everything you sit on is for sale. Candles, cheap bottles, DJs at weekends." },
    { place: "harbo-bar", area: "Nørrebro", vibe: "Corner bar", beer: "≈40–50 kr", avg: 45, hours: "Daily", blurb: "Coffee by day, beer and DJs by night, tables on Blågårdsgade." },
    { place: "bo-bi-bar", area: "Indre By", vibe: "Bodega", beer: "≈40–50 kr", avg: 45, hours: "Daily 12–02", blurb: "One red room from 1917, poets and old men, the centre's best bodega." },
    { place: "mesteren-laerlingen", area: "Vesterbro", vibe: "Dive / dancing", beer: "≈40–50 kr", avg: 45, hours: "Thu–Sat late", blurb: "Tiny Kødbyen bar, reggae and soul, dancing on the tables after midnight." },
    { place: "jolene", area: "Vesterbro", vibe: "Party bar", beer: "≈40–50 kr", avg: 45, hours: "Wed–Sat till 05", blurb: "Kødbyen's Berlin-ish bar: free entry, DJs, cheap beer, goes late." },
    { place: "bakken-kbh", area: "Vesterbro", vibe: "Club-bar", beer: "≈40–50 kr", avg: 45, hours: "Thu–Sat", blurb: "Loud, packed, free before midnight, cheap draught." },
    { place: "palae-bar", area: "Indre By", vibe: "Jazz bodega", beer: "≈45–55 kr", avg: 50, hours: "Daily 11–01", blurb: "Behind Kongens Nytorv: vinyl jazz, journalists, the anti-Nyhavn five minutes from Nyhavn." },
    { place: "bankeraat", area: "Indre By", vibe: "Taxidermy bar", beer: "≈45–55 kr", avg: 50, hours: "Daily", blurb: "Stuffed animals in costumes, cheap-ish drinks, near the Lakes." },
    { place: "log-lady", area: "Indre By", vibe: "Twin Peaks bar", beer: "≈45–55 kr", avg: 50, hours: "Tue–Sat evenings", blurb: "Red curtains, damn fine coffee, cheap beer in the old town." },
    { place: "lord-nelson", area: "Indre By", vibe: "Pub", beer: "≈45–55 kr", avg: 50, hours: "Daily", blurb: "Danish micro-brews on tap, seats outside on a Strøget side street." },
    { place: "vinstue-90", area: "Frederiksberg", vibe: "Slow-beer bodega", beer: "≈45–55 kr", avg: 50, hours: "Daily", blurb: "A Carlsberg poured over 10–15 minutes from a wooden barrel — the famous 'slow beer'. Worth the walk down Gammel Kongevej." },
    { place: "charlies-bar", area: "Indre By", vibe: "Real-ale pub", beer: "≈50–60 kr", avg: 55, hours: "Daily", blurb: "British cask ales, CAMRA-approved, football on the telly." },
    { place: "orsted-olbar", area: "Indre By", vibe: "Craft bar", beer: "≈50–60 kr", avg: 55, hours: "Daily", blurb: "Snug craft-beer bar on a quiet street by Ørstedsparken." },
    { place: "fermentoren", area: "Vesterbro", vibe: "Craft cellar", beer: "≈50–65 kr", avg: 58, hours: "Daily from 14", blurb: "20+ taps in a cellar on Halmtorvet, candle-lit yard outside." },
    { place: "hviids-vinstue", area: "Indre By", vibe: "Historic bar", beer: "≈55–65 kr", avg: 60, hours: "Daily 11–24", blurb: "Copenhagen's oldest (1723). Panelled cellar rooms, kitchen all day, a hot 'gløgg' vibe even in September." },
    { place: "norrebro-bryghus", area: "Nørrebro", vibe: "Brewpub", beer: "≈55–65 kr", avg: 60, hours: "Daily", blurb: "The city's first brewpub, by the Lakes; happy hour before 18:00." },
    { place: "brus", area: "Nørrebro", vibe: "Brewpub", beer: "≈55–70 kr", avg: 62, hours: "Daily", blurb: "To Øl's brewery-bar in an old iron foundry: 30 taps, bottle shop, food." },
    { place: "olbaren", area: "Nørrebro", vibe: "Beer-nerd bar", beer: "≈55–75 kr", avg: 65, hours: "Daily", blurb: "100+ bottles on Elmegade and a bartender who'll pick for you." },
    { place: "taphouse", area: "Indre By", vibe: "61 taps", beer: "≈55–75 kr", avg: 65, hours: "Daily from 15", blurb: "Denmark's biggest tap wall; small pours let you taste a lot." },
    { place: "mikkeller-bar", area: "Vesterbro", vibe: "Craft pilgrimage", beer: "≈60–80 kr", avg: 70, hours: "Daily", blurb: "The original Mikkeller basement bar. Have one, then go somewhere cheaper." },
    { place: "mikkeller-baghaven", area: "Refshaleøen", vibe: "Barrel taproom", beer: "≈60–80 kr", avg: 70, hours: "Thu–Sun (check)", blurb: "Sour and wild ales by the water on Refshaleøen. Line 6 territory." },
  ],
  barTip: "Drinking outdoors is legal and normal. A Tuborg or Carlsberg from Netto/Føtex is 10–15 kr, from a kiosk 20–30; the same beer in a bar is 45–75. The classic moves: sunset on <b>Dronning Louises Bro</b>, legs over the edge of the <b>Nyhavn</b> quay, the lawn on <b>Sønder Boulevard</b> (Kihoskh opposite), or the ramparts at Kastellet. Cans and bottles carry a 1–3 kr <b>pant</b> deposit — leave empties standing next to a bin and someone collects them. Bodegas (old-school neighbourhood bars) are the cheap indoor option; 'Classic' is the darker Tuborg.",

  // ---------------------------------------------------------- FOOD 101 ----
  food101: [
    { name: "Smørrebrød", say: "smur-broath", what: "Open sandwiches on dark rye, built like small architecture. Order 2–3 per person and eat in order: herring → fish → meat → cheese. Knife and fork, never hands.", where: "Schønnemann, Told & Snaps, Hallernes (cheap)" },
    { name: "Sild", say: "seel", what: "Pickled herring — plain, curried, or with dill — on rye with raw onion. The mandatory first piece, with a snaps.", where: "Any smørrebrød place; Kanal Cafeen" },
    { name: "Stegt flæsk med persillesovs", say: "stegt flesk", what: "The national dish: crispy slices of pork belly, parsley cream sauce, boiled potatoes. Often all-you-can-eat.", where: "Café Sorgenfri, Restaurant Puk" },
    { name: "Frikadeller", say: "frik-a-della", what: "Pan-fried pork meatballs, with potato salad or red cabbage. Danish grandmother food.", where: "Café Sorgenfri, Restaurant Kronborg" },
    { name: "Ristet hotdog", say: "ristet", what: "Street hot dog: red or toasted sausage in a bun with ketchup, mustard, remoulade, raw + crispy onions, pickles. 'Med det hele' = with everything.", where: "DØP, John's Hotdog Deli" },
    { name: "Stjerneskud", say: "stair-ne-skud", what: "'Shooting star': fried and steamed plaice on toast with shrimp, asparagus and caviar. The lunch-with-a-view dish.", where: "Told & Snaps, Kanal Cafeen" },
    { name: "Flæskestegssandwich", say: "flesk-stays", what: "Roast pork with crackling in a bun with red cabbage, pickles and mayo. Street-food Denmark's answer to everything.", where: "Torvehallerne, Broens Gadekøkken" },
    { name: "Tarteletter", say: "tar-te-let-ter", what: "Puff-pastry cups with chicken and asparagus in white sauce. Retro, comforting, appears on lunch menus.", where: "Aamanns 1921, Restaurant Puk" },
    { name: "Rugbrød", say: "roo-broath", what: "The dense sour rye bread everything sits on. Try it plain with butter and you'll understand the country.", where: "Every bakery" },
    { name: "Kanelsnegl / kardemommesnurre", say: "kanel-snile", what: "Cinnamon snail / cardamom twist. The morning ritual with a filter coffee.", where: "Juno, Hart, Meyers, Lagkagehuset" },
    { name: "Wienerbrød", say: "vee-ner-broath", what: "What the world calls a 'Danish' — they call it Vienna bread. Tebirkes (poppy-seed) is the local favourite.", where: "Lagkagehuset, La Glace" },
    { name: "Grød", say: "groath", what: "Porridge, but as a proper meal: oat with caramel and apple, or savoury risotto-style bowls.", where: "GRØD (Jægersborggade, Torvehallerne)" },
    { name: "Snaps / akvavit", say: "snaps", what: "Caraway- or dill-flavoured spirit, one small cold glass with herring. Look everyone in the eye and say 'Skål!'.", where: "Told & Snaps (20 kinds), Schønnemann (140)" },
    { name: "Øl", say: "url", what: "Beer. Carlsberg and Tuborg are the defaults; 'Classic' is the darker one. Craft: Mikkeller, To Øl, Nørrebro Bryghus.", where: "Everywhere; Vinstue 90 for the slow pour" },
    { name: "Flødeboller", say: "flur-the-boller", what: "Chocolate-coated marshmallow domes on a marzipan base. Summerbird in Torvehallerne does the posh version.", where: "Torvehallerne, any supermarket" },
    { name: "Hygge", say: "hoo-ga", what: "Not food — the mood: candles, a table, nobody in a hurry. Order a second coffee and you're doing it.", where: "Any bodega after 21:00" },
  ],

  // ------------------------------------------------------- DEFENCE DAY ----
  defence: {
    kicker: "Monday 28 September · the big day",
    title: "Defence day",
    intro: "Defence at <b>13:00 at DTU Lyngby</b>, flight at <b>19:00</b>. That leaves one real window to celebrate: a late lunch in the city between 15:45 and 17:00, then 15 minutes of metro to the airport. Here's the schedule that makes it work.",
    building: "Building 101 (change in data.js if the room is elsewhere)",
    timeline: [
      { time: "08:30", title: "Breakfast, check out", text: "Bring the suitcases along for the day — the bus, the restaurant cloakroom and the metro all cope. Alternative: ask the hotel to hold bags and collect them on the way to the metro (only if the hotel is between Nørreport and Kongens Nytorv).", facts: "Coffee & buns: Paludan (Fiolstræde) or Torvehallerne" },
      { time: "11:15", title: "Nørreport → DTU", text: "Bus <b>15E</b> (fastest, ≈22 min) or <b>150S</b> (≈30 min) from the Nørreport bus stops on Nørre Voldgade towards Lyngby/Kokkedal. Get off at <b>Rævehøjvej (DTU)</b>. Buy the ticket in the Rejsebillet app before boarding.", facts: "≈30–38 kr per person · check the next departure in Rejseplanen" },
      { time: "11:50", title: "Walk into campus", text: "Eight minutes from the bus stop along Anker Engelunds Vej to the defence building. Time for a coffee in the canteen and finding the room.", facts: "DTU is huge and flat — the map has the pin" },
      { time: "13:00", title: "The defence", text: "Typically 45 minutes of presentation, then questions from the committee (an hour or more), then the committee leaves to deliberate and comes back with the verdict. Phones off, sit where you can see the slides, and don't worry when the questions sound harsh — that's the format.", hi: true },
      { time: "≈15:00", title: "Reception", text: "Handshakes, sparkling wine and cake, usually right outside the room. This is the hug moment. Keep it to 30 minutes if you want the city lunch.", facts: "If the reception runs long, switch to Option C below" },
      { time: "15:30", title: "DTU → Nørreport", text: "Back to Rævehøjvej, bus 15E or 150S southbound. From Nørreport it's an 8-minute walk to Schønnemann or one metro stop (M1/M2) to Kongens Nytorv for the other options.", facts: "≈25 min · ≈30–38 kr" },
      { time: "16:00", title: "Celebration lunch", text: "See the options below. Book a table for 16:00 <b>and tell them you'll be leaving by 17:00</b> — Danish kitchens close the lunch service around 16:00, so this only works with a reservation.", hi: true },
      { time: "17:05", title: "To the airport", text: "Metro <b>M2</b> from Kongens Nytorv (or Nørreport) direct to Lufthavnen: 15–17 minutes, trains every 4–6 minutes, arrives inside Terminal 3. Aim to be at the airport by 17:30 for a 19:00 departure — 17:15 if there are bags to check.", facts: "30 kr per person (3 zones) · buy in Rejsebillet or at the machine" },
      { time: "19:00", title: "Flight", text: "Skål from the ground." },
    ],
    celebrateIntro: "The awkward truth: 16:00 on a Monday is the gap between Danish lunch and dinner. These are the places that work for a proper celebratory meal in that window — book ahead and mention the time.",
    options: [
      { place: "schonnemann", tag: "Option A · the classic", rec: true, text: "The smørrebrød institution since 1877: herring, plaice, tartare, 140 kinds of snaps, chefs from Noma at the next table. Open Mondays until 17:00 — <b>call and book for 15:45–16:00</b> and confirm they'll seat you that late. Eight minutes from the Nørreport bus stop.", price: "≈300–450 kr pp", hours: "Mon–Sat 11:30–17:00", toAirport: "Nørreport M2 → airport 17 min", book: "https://www.google.com/maps/search/?api=1&query=Restaurant%20Sch%C3%B8nnemann%20Hauser%20Plads%2016" },
      { place: "aamanns-1921", tag: "Option B · modern", text: "Smørrebrød reinvented, Michelin-listed, a grand 1921 bank room. Lunch runs to 17:00 with last orders at 16:00, so this one needs you at the table by 15:50 sharp — or book the 17:30 dinner sitting if the flight can take it (it can't, realistically). Five minutes from Nørreport.", price: "≈250–400 kr pp", hours: "Lunch daily 11:30–17 (last order 16:00)", toAirport: "Nørreport M2 → airport 17 min", book: "https://aamanns.dk/en/restaurant/aamanns-1921/" },
      { place: "cafe-sorgenfri", tag: "Option C · always works", text: "The bodega-restaurant: stegt flæsk, frikadeller, herring, cold beer, wood panels, no gap between lunch and dinner. Not fancy, extremely Danish, and open whenever the reception finishes. No booking stress.", price: "≈150–230 kr pp", hours: "Daily ≈11–21, kitchen all day", toAirport: "Walk 10 min to Nørreport, M2 → airport 17 min" },
      { place: "hviids-vinstue", tag: "Option D · by the metro", text: "Copenhagen's oldest bar (1723) with a proper kitchen all day — smørrebrød, a plate of the day, and the celebration beer. Two minutes from the Kongens Nytorv metro entrance, so the airport dash is the shortest of all.", price: "≈150–250 kr pp", hours: "Daily 11–24", toAirport: "Kongens Nytorv M2 → airport 15 min" },
    ],
    morning: [
      "<b>Easy version:</b> a slow breakfast in the centre, a walk round the King's Garden (Rosenborg) which is 5 minutes from the Nørreport bus stop, then the bus at 11:15.",
      "<b>Campus version:</b> come to DTU early on the 10:30 bus, see where the last years happened — the library, Skylab, the lakes on campus — and have lunch in the canteen before the room opens.",
      "<b>Deer version (early risers):</b> S-train to Klampenborg (25 min from Nørreport) for an hour among the deer in Dyrehaven, then bus 388 → Lyngby → 300S to DTU. Only if the weather's good and everyone's up by 8.",
    ],
    checklist: [
      "<b>Book the lunch</b> — every option above needs a call for a 16:00 table on a Monday; say it's a celebration and that you leave at 17:00.",
      "<b>Tickets:</b> the Rejsebillet app works for the bus and the metro; 3-zone tickets cover Nørreport → airport, DTU is 3–4 zones. Buy before boarding.",
      "<b>Luggage:</b> bring it, or use the lockers at Central Station only if you're passing through (you aren't on this route). Restaurants will hold bags.",
      "<b>Flowers/gifts</b> are normal at Danish defences; there's usually cake. Nobody dresses up beyond smart-casual.",
      "<b>Museums are closed on Mondays</b> — no Plan B sightseeing needed anyway; the day is full.",
    ],
    mapPlaces: [
      { place: "dtu-building-101", label: "★", kicker: "Defence 13:00", route: true },
      { place: "dtu-bus-stop", label: "B", kicker: "Bus 15E / 150S", route: true },
      { place: "norreport", label: "N", kicker: "Bus → metro", route: true },
      { place: "schonnemann", label: "A", kicker: "Celebration · option A", route: true },
      { place: "aamanns-1921", label: "B", kicker: "Celebration · option B" },
      { place: "cafe-sorgenfri", label: "C", kicker: "Celebration · option C" },
      { place: "hviids-vinstue", label: "D", kicker: "Celebration · option D" },
      { place: "kongens-nytorv", label: "M", kicker: "Metro M2 to airport", route: true },
      { place: "airport", label: "✈", kicker: "Flight 19:00", route: true },
    ],
  },

  // ---------------------------------------------------------------- INFO ----
  info: {
    sections: [
      { title: "Getting around", items: [
        "<b>Walk.</b> The centre is 3 km across and flat; every line here is designed to be done on foot.",
        "<b>Metro</b> (M1–M4) runs 24/7, driverless, every 2–6 min. <b>Harbour buses</b> 991/992 are normal buses that float — same ticket.",
        "<b>Tickets:</b> Rejsebillet app (replaced DOT Billetter in 2025) or the machines. 2 zones 24 kr, 3 zones 30 kr. Airport ↔ centre = 3 zones. DTU = 3–4 zones (≈30–38 kr).",
        "<b>Never walk in the bike lanes</b> — the ones with the little kerb. Look both ways before stepping off any pavement; bikes come from behind.",
        "Locals wait for the green man even at 3 am. Do the same.",
        "Taxis are ≈300–350 kr airport → centre. The metro is 30 kr and faster.",
      ] },
      { title: "Airport ↔ city", items: [
        "<b>Metro M2</b> from inside Terminal 3 to Kongens Nytorv (15 min) or Nørreport (17 min). Trains every 4–6 min, also at night.",
        "<b>Regional trains</b> from Terminal 3 to Central Station (13 min) if the hotel is near Tivoli/Vesterbro.",
        "3-zone ticket, 30 kr, from the red machines or the Rejsebillet app. Validate nothing — just carry it.",
        "Be at the airport <b>90 min before</b> a Schengen flight with bags, 60 without.",
      ] },
      { title: "Money", items: [
        "Danish kroner (DKK). Roughly <b>7.45 kr = 1 €</b>; 100 kr ≈ 13 €.",
        "Cards and Apple/Google Pay everywhere, including hot-dog carts. Many places are card-only. You don't need cash except maybe in Christiania.",
        "No tipping culture — service is in the price. Rounding up 5–10% for great service is appreciated, never expected.",
        "<b>Pant:</b> cans and bottles carry a 1–3 kr deposit; supermarkets have return machines.",
      ] },
      { title: "This week specifically", items: [
        "<b>Sunset ≈19:00</b>, sunrise ≈07:10. Daylight until about 19:30.",
        "<b>Tivoli is closed</b> 21 Sep–1 Oct 2026 (between seasons).",
        "<b>Sunday:</b> big shops in the centre open 11–17; museums and sights open as normal.",
        "<b>Monday:</b> most museums are closed (Glyptotek, Designmuseum, Thorvaldsens, SMK, Christiansborg tower, Cisternerne). Supermarkets, bakeries and sights like the Round Tower are open.",
        "<b>Reffen</b> and <b>Broens Gadekøkken</b> are at the end of their seasons — check their sites the day before.",
      ] },
      { title: "Weather & what to bring", items: [
        "Late September: <b>10–16 °C</b>, windy, showers that pass. Layers, a rain jacket with a hood (umbrellas lose to the wind), shoes you can do 6 km in.",
        "A tote bag for supermarket beers and pastries. A power bank — the map is your compass.",
        "Plugs are the two-pin European type (C/F fit; the Danish K socket also takes them).",
      ] },
      { title: "Safety & health", items: [
        "Very safe city. Watch bags in Nyhavn crowds and on the metro, that's about it.",
        "<b>112</b> for emergencies. <b>1813</b> is the medical helpline to call before going to an emergency room.",
        "Pharmacies are called <b>Apotek</b>; Steno Apotek at Central Station is open 24 h.",
        "Tap water is excellent — ask for <b>postevand</b> in restaurants and it's free.",
      ] },
      { title: "How Danes are", items: [
        "Quiet in public, direct in conversation, punctual to the minute. 'Hej' for hello, 'hej hej' for goodbye.",
        "Everyone speaks English. A 'tak' (thanks) goes a long way anyway.",
        "Queues are sacred; so is personal space on the bus.",
        "Hygge is real: candles on café tables at noon, nobody rushing you out.",
      ] },
    ],
    phrases: [
      ["Hej / Hej hej", "Hi / Bye"],
      ["Tak", "Thanks"],
      ["Tak for mad", "Thanks for the meal"],
      ["Skål!", "Cheers!"],
      ["Undskyld", "Sorry / excuse me"],
      ["Ja / Nej", "Yes / No"],
      ["En øl, tak", "A beer, please"],
      ["Postevand", "Tap water"],
      ["Hvor er…?", "Where is…?"],
      ["Tillykke!", "Congratulations!"],
    ],
  },
};
